jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Paso 1: Construir imagen Docker
      - name: Build Docker image
        run: |
          docker build -t portafolio-builder -f docker/Dockerfile .
      
      # Paso 2: Ejecutar el contenedor
      - name: Deploy with Docker
        run: |
          docker run --rm -e PERSONAL_TOKEN=${{ secrets.PERSONAL_TOKEN }} portafolio-builder
