name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g gh-pages
      - run: npm install
      - run: npx gh-pages -d . -r https://${{ secrets.GITHUB_TOKEN }}@github.com/digitec-conexion/portafolio_grupo_D_uc.git
